# Generated by Django 4.2.2 on 2023-07-20 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_bids', models.IntegerField(default=0)),
                ('bidding_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('img_url', models.URLField()),
                ('category', models.CharField(choices=[('NON', '-----'), ('MUS', 'Music'), ('TEC', 'Technology'), ('SPO', 'Sports'), ('ART', 'Art'), ('FAS', 'Fashion'), ('HOM', 'Home'), ('OFF', 'Office'), ('TRA', 'Transport'), ('GAM', 'Games'), ('OTH', 'Other')], max_length=3)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('listing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_sent', models.DateTimeField()),
                ('comment_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_auction', to='auctions.auction')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid_win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amounts', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bid_auctions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_auctions', to='auctions.auction')),
                ('bid_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bid_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_auction', to='auctions.auction')),
                ('bid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='listing_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_auction', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='watching', to='auctions.auction'),
        ),
    ]
